name-template: "$RESOLVED_VERSION"

template: |
  $CHANGES
categories:
  - title: "✨ Features"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
  - title: "🧰 Maintenance"
    labels:
      - "chore"

exclude-labels:
  - release
