name: Publish Pre-Release

on:
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: write
  pull-requests: write
  
jobs:
  publish_pre_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Draft a new release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: .github/release-drafter.yml
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
